//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpatialDataInEfExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public int Id { get; set; }
        public string AirportName { get; set; }
        public string CityName { get; set; }
        public string Country { get; set; }
        public string AirportCode { get; set; }
        public System.Data.Spatial.DbGeography Location { get; set; }
        public int Altitude { get; set; }
        public double TimezoneOffset { get; set; }
        public string DST { get; set; }
    }
}
