//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableFunctionExample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AirTravelDbEntities : DbContext
    {
        public AirTravelDbEntities()
            : base("name=AirTravelDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [EdmFunction("AirTravelDbEntities", "GetDistancesFromMajorAustralianAiports")]
        public virtual IQueryable<DistancesFromAustralianAirports> GetDistancesFromMajorAustralianAiports(string destinationAirport)
        {
            var destinationAirportParameter = destinationAirport != null ?
                new ObjectParameter("DestinationAirport", destinationAirport) :
                new ObjectParameter("DestinationAirport", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DistancesFromAustralianAirports>("[AirTravelDbEntities].[GetDistancesFromMajorAustralianAiports](@DestinationAirport)", destinationAirportParameter);
        }
    }
}
