//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableFunctionExample
{
    using System;
    
    public partial class DistancesFromAustralianAirports
    {
        public int Id { get; set; }
        public string StartPoint { get; set; }
        public string EndPoint { get; set; }
        public string StartPointAirportCode { get; set; }
        public Nullable<int> Distance { get; set; }
    }
}
