//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiResultStoredProcExample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AirTravelDbEntities1 : DbContext
    {
        public AirTravelDbEntities1()
            : base("name=AirTravelDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<AustralianInternationalAirports> AustralianAirportsAndDistances(string airportCode)
        {
            var airportCodeParameter = airportCode != null ?
                new ObjectParameter("AirportCode", airportCode) :
                new ObjectParameter("AirportCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AustralianInternationalAirports>("AustralianAirportsAndDistances", airportCodeParameter);
        }
    }
}
