//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiResultStoredProcExample
{
    using System;
    
    public partial class PointToPoint
    {
        public string Origin { get; set; }
        public string Destination { get; set; }
        public double Distance { get; set; }
    }
}
